### ISSUE TITLE
ADD Note: character between<> will be lost. the same porblem as before.

### ISSUE THREAD

**Issue by chenjaixnin** [pbrane/tac-case-api-service-monolith#73]
ADD Note: character between<> will be lost.
![Image](https://github.com/user-attachments/assets/b87c6dc3-21b9-4b66-8546-af6ff3412eed)

character between<> will be lost.
![Image](https://github.com/user-attachments/assets/a86aa216-da17-4c08-acea-ca5500a31ce6)

**Comment by JunfengKe** [comment]
Need to do special handling for below characters:
Backslash (\): Used as an escape character itself.
Quotation Marks (" and '): To include quotation marks within strings.
New Line (\n): Represents a new line.
Carriage Return (\r): Represents a carriage return.
Tab (\t): Represents a tab space.
Backspace (\b): Represents a backspace.
Form Feed (\f): Represents a form feed.
And <>

**Comment by JunfengKe** [comment]
Need to do special handling for below characters:
Backslash (): Used as an escape character itself.
Quotation Marks (" and '): To include quotation marks within strings.
New Line (\n): Represents a new line.
Carriage Return (\r): Represents a carriage return.
Tab (\t): Represents a tab space.
Backspace (\b): Represents a backspace.
Form Feed (\f): Represents a form feed.
And <>

I have test New Line (\n): now work

**Comment by pbrane** [comment]
This is another example of the problems with HTTP reserved characters. I have corrected this behavior for the text messages of notes, now. This is issue is now resolved and there are now three environment variables for handling the HTML reserved characters:

ESCAPE_HTML_SUBJECT=true
ESCAPE_HTML_DESCRIPTION=true
ESCAPE_HTML_NOTES=true

The previous used envvar was: ESCAPE_HTML_STRINGS. This is now deprecated and will be removed because this caused probablems with responses from Freshdesk when working with the pagination API.

Commit: 13bc816

**Comment by elu01** [comment]
duplicate with #46, #84, #95. closed
We don’t see those odd characters on Freshdesk, only in Postman test/API when the three environment variables are set to TRUE.

**Comment by JunfengKe** [comment]
Still can't handle ENTER in the text body
When I click ENTER in the keyboard , then the text body, changed to red line as below

![Image](https://github.com/user-attachments/assets/bc280446-ef09-4017-b38e-014cdb0ae933)

![Image](https://github.com/user-attachments/assets/36253a05-2891-4213-b704-a0e9fba98eb1)

**Comment by pbrane** [comment]
I apologize if I have not explained this as comprehensively as I could have in the past. 

I will try again, but before I explain the problem with character encodings, let me first express that right here Postman is informing you, in this editor, that the JSON document you have created is an invalid JSON document and is underlying that error in red. That is why you received the error: "Failed to read request." 

JSON doesn't allow values to have *raw* character encodings like this. If you are on On Windows, pressing Enter inserts a Carriage Return + Line Feed (CRLF) sequence (\r\n, ASCII 0x0D 0x0A) and if you are on Mac or Linux, pressing Enter/Return in Postman inserts a Line Feed (LF) character (\n, ASCII 0x0A). The Postman editor is interpreting those characters in the way that you expect an *editor* to interpret them. However, JSON documents are just raw serialized data (which is why Postman editor has the "raw" indidicated in this image) that is destined for another application, and the JSON specification doesn't allow these raw encodings. Since JSON is HTML based protocol, and ultimately Freshdesk is an HTML based web applicaiton, you must encode these raw characters or use the HTML way of indicating you want the remaing text to be displayed on a "new" line.

To do this with HTML, instead of htting enter, you should use the HTML encoding "<br>." When that encoding is received by the API we have written for MSFT, the angle brackets will be further encoded so that you don't have to. Prior to the enhancements of "HTML escaping" that we just recently added, you would have needed to send the full encoding yourself like this: "&lt;br&gt;"  That is the HTML encoding for "<br>" and "<br>" and is interepreted by HTML browsers, like Chrome, as a "break" (new line) and text will be moved to the next line. (by the way, CSS further informs the browser how to display on the new line, such as: left justified, right justified, centered, etc. with even more HTML encodings)

So, now that we have explained this JSON error, which is an error in of itself *before* it hits the API, we can explain further how to get what you want to display in Freshdesk. As mentioned above, you want to change that line to:

```
"text": "123<br>;vv"
```

This will be properly handled by Freshdesk to format the note as intended for the Agents in the Freshdesk display.

### Here are screenshots of how this works:

#### Create the note:

<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/d7a84574-04ad-426d-b7c6-a347e91b1044" />

#### View the note in Freshdesk: (notice the correct "new line" formatting by the browser)

<img width="997" alt="Image" src="https://github.com/user-attachments/assets/c8b79654-1791-4cef-9137-07dce80ee5b9" />

#### Freshdesk is returning a readable string for us in the JSON response.

<img width="1170" alt="Image" src="https://github.com/user-attachments/assets/626a45d0-8302-4dc0-a010-6e834207517d" />

### TL;DR
Two important takeaways in this issue:

1. Your request body isn't JSON compliant.
2. We have to remember that formatting characters are up to interpretation. If you are in an editor, pressing enter and getting the ASCII characters for a new line put in the document, 0x0D and/or 0x0A, renders fine in the editor but, even if sent to Freshdesk, wouldn't display propery in HTML without proper HTML encoding.

I hope this helps. (Note: this document is formatted for the Markdown language with encodings such as "###" for a heading that you won't see in the HTML display even though this comment has them "embedded" in this markdown document. :)

**Comment by pbrane** [comment]
@chenjaixnin @elu01 : Please let me know if you would like to have time online to explain this in person.

**Comment by pbrane** [comment]
Oh, I forgot to add @JunfengKe , please let me know if you want time online to discuss.
@elu01

**Comment by chenjaixnin** [comment]
@Emily ,

when I add note which including <>, it successfully.

![Image](https://github.com/user-attachments/assets/6651ad6e-ee3c-4dbc-9a54-072a1fd90835)

resultes:

![Image](https://github.com/user-attachments/assets/28db97d4-ff83-412d-9a3d-48adae988a36)

so this case can be closed.

Jianxin.
